#
# Copyright (c) 2018 Intel Corporation
# Copyright (c) 2018 IBM
#
# SPDX-License-Identifier: Apache-2.0
#

sudo: required
dist: xenial

language: go
os:
- linux
- linux-ppc64le

env:
  - target_branch=$TRAVIS_BRANCH
    GO111MODULE=on

before_install:
  - ".ci/setup.sh"

before_script:
  - ".ci/install_go.sh"
  - ".ci/static-checks.sh"
  - ".ci/versions_checker.sh"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - ".ci/install-yq.sh"
  - make
  - sudo -E PATH=$PATH make install
