// Code generated by protoc-gen-go.
// source: hyperstart.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	hyperstart.proto
	oci.proto

It has these top-level messages:
	CreateContainerRequest
	StartContainerRequest
	ExecProcessRequest
	SignalProcessRequest
	WaitProcessRequest
	WaitProcessResponse
	WriteStreamRequest
	WriteStreamResponse
	ReadStreamRequest
	ReadStreamResponse
	CloseStdinRequest
	TtyWinResizeRequest
	StartSandboxRequest
	DestroySandboxRequest
	IpAddress
	UpdateInterfaceRequest
	AddRouteRequest
	OnlineCPUMemRequest
	StringUser
	Route
	Spec
	Process
	Box
	User
	LinuxCapabilities
	POSIXRlimit
	Mount
	Root
	Hooks
	Hook
	Linux
	Windows
	Solaris
	LinuxIDMapping
	LinuxNamespace
	LinuxDevice
	LinuxResources
	LinuxMemory
	LinuxCPU
	LinuxWeightDevice
	LinuxThrottleDevice
	LinuxBlockIO
	LinuxPids
	LinuxDeviceCgroup
	LinuxNetwork
	LinuxHugepageLimit
	LinuxInterfacePriority
	LinuxSeccomp
	LinuxSeccompArg
	LinuxSyscall
	LinuxIntelRdt
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateContainerRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	OCI         *Spec  `protobuf:"bytes,2,opt,name=OCI" json:"OCI,omitempty"`
}

func (m *CreateContainerRequest) Reset()                    { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()               {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateContainerRequest) GetOCI() *Spec {
	if m != nil {
		return m.OCI
	}
	return nil
}

type StartContainerRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *StartContainerRequest) Reset()                    { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()               {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ExecProcessRequest struct {
	ContainerId string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	Process     *Process `protobuf:"bytes,2,opt,name=process" json:"process,omitempty"`
}

func (m *ExecProcessRequest) Reset()                    { *m = ExecProcessRequest{} }
func (m *ExecProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecProcessRequest) ProtoMessage()               {}
func (*ExecProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExecProcessRequest) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

type SignalProcessRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	Signal      uint32 `protobuf:"varint,3,opt,name=signal" json:"signal,omitempty"`
}

func (m *SignalProcessRequest) Reset()                    { *m = SignalProcessRequest{} }
func (m *SignalProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalProcessRequest) ProtoMessage()               {}
func (*SignalProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type WaitProcessRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
}

func (m *WaitProcessRequest) Reset()                    { *m = WaitProcessRequest{} }
func (m *WaitProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*WaitProcessRequest) ProtoMessage()               {}
func (*WaitProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type WaitProcessResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *WaitProcessResponse) Reset()                    { *m = WaitProcessResponse{} }
func (m *WaitProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*WaitProcessResponse) ProtoMessage()               {}
func (*WaitProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type WriteStreamRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	Data        []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteStreamRequest) Reset()                    { *m = WriteStreamRequest{} }
func (m *WriteStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteStreamRequest) ProtoMessage()               {}
func (*WriteStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type WriteStreamResponse struct {
	Len uint32 `protobuf:"varint,1,opt,name=len" json:"len,omitempty"`
}

func (m *WriteStreamResponse) Reset()                    { *m = WriteStreamResponse{} }
func (m *WriteStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteStreamResponse) ProtoMessage()               {}
func (*WriteStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ReadStreamRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	Len         uint32 `protobuf:"varint,3,opt,name=len" json:"len,omitempty"`
}

func (m *ReadStreamRequest) Reset()                    { *m = ReadStreamRequest{} }
func (m *ReadStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadStreamRequest) ProtoMessage()               {}
func (*ReadStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ReadStreamResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ReadStreamResponse) Reset()                    { *m = ReadStreamResponse{} }
func (m *ReadStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadStreamResponse) ProtoMessage()               {}
func (*ReadStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type CloseStdinRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
}

func (m *CloseStdinRequest) Reset()                    { *m = CloseStdinRequest{} }
func (m *CloseStdinRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseStdinRequest) ProtoMessage()               {}
func (*CloseStdinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type TtyWinResizeRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessId   string `protobuf:"bytes,2,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	Row         uint32 `protobuf:"varint,3,opt,name=row" json:"row,omitempty"`
	Column      uint32 `protobuf:"varint,4,opt,name=column" json:"column,omitempty"`
}

func (m *TtyWinResizeRequest) Reset()                    { *m = TtyWinResizeRequest{} }
func (m *TtyWinResizeRequest) String() string            { return proto.CompactTextString(m) }
func (*TtyWinResizeRequest) ProtoMessage()               {}
func (*TtyWinResizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type StartSandboxRequest struct {
	Hostname string   `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Dns      []string `protobuf:"bytes,2,rep,name=dns" json:"dns,omitempty"`
}

func (m *StartSandboxRequest) Reset()                    { *m = StartSandboxRequest{} }
func (m *StartSandboxRequest) String() string            { return proto.CompactTextString(m) }
func (*StartSandboxRequest) ProtoMessage()               {}
func (*StartSandboxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type DestroySandboxRequest struct {
}

func (m *DestroySandboxRequest) Reset()                    { *m = DestroySandboxRequest{} }
func (m *DestroySandboxRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroySandboxRequest) ProtoMessage()               {}
func (*DestroySandboxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type IpAddress struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Mask    string `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *IpAddress) Reset()                    { *m = IpAddress{} }
func (m *IpAddress) String() string            { return proto.CompactTextString(m) }
func (*IpAddress) ProtoMessage()               {}
func (*IpAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type UpdateInterfaceRequest struct {
	Type        uint64       `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Device      string       `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
	NewName     string       `protobuf:"bytes,3,opt,name=newName" json:"newName,omitempty"`
	IpAddresses []*IpAddress `protobuf:"bytes,4,rep,name=ipAddresses" json:"ipAddresses,omitempty"`
	Mtu         uint64       `protobuf:"varint,5,opt,name=mtu" json:"mtu,omitempty"`
}

func (m *UpdateInterfaceRequest) Reset()                    { *m = UpdateInterfaceRequest{} }
func (m *UpdateInterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateInterfaceRequest) ProtoMessage()               {}
func (*UpdateInterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateInterfaceRequest) GetIpAddresses() []*IpAddress {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

type AddRouteRequest struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *AddRouteRequest) Reset()                    { *m = AddRouteRequest{} }
func (m *AddRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRouteRequest) ProtoMessage()               {}
func (*AddRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AddRouteRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type OnlineCPUMemRequest struct {
}

func (m *OnlineCPUMemRequest) Reset()                    { *m = OnlineCPUMemRequest{} }
func (m *OnlineCPUMemRequest) String() string            { return proto.CompactTextString(m) }
func (*OnlineCPUMemRequest) ProtoMessage()               {}
func (*OnlineCPUMemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type StringUser struct {
	Uid            string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Gid            string   `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	AdditionalGids []string `protobuf:"bytes,3,rep,name=additionalGids" json:"additionalGids,omitempty"`
}

func (m *StringUser) Reset()                    { *m = StringUser{} }
func (m *StringUser) String() string            { return proto.CompactTextString(m) }
func (*StringUser) ProtoMessage()               {}
func (*StringUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type Route struct {
	Dest    string `protobuf:"bytes,1,opt,name=dest" json:"dest,omitempty"`
	Gateway string `protobuf:"bytes,2,opt,name=gateway" json:"gateway,omitempty"`
	Device  string `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func init() {
	proto.RegisterType((*CreateContainerRequest)(nil), "grpc.CreateContainerRequest")
	proto.RegisterType((*StartContainerRequest)(nil), "grpc.StartContainerRequest")
	proto.RegisterType((*ExecProcessRequest)(nil), "grpc.ExecProcessRequest")
	proto.RegisterType((*SignalProcessRequest)(nil), "grpc.SignalProcessRequest")
	proto.RegisterType((*WaitProcessRequest)(nil), "grpc.WaitProcessRequest")
	proto.RegisterType((*WaitProcessResponse)(nil), "grpc.WaitProcessResponse")
	proto.RegisterType((*WriteStreamRequest)(nil), "grpc.WriteStreamRequest")
	proto.RegisterType((*WriteStreamResponse)(nil), "grpc.WriteStreamResponse")
	proto.RegisterType((*ReadStreamRequest)(nil), "grpc.ReadStreamRequest")
	proto.RegisterType((*ReadStreamResponse)(nil), "grpc.ReadStreamResponse")
	proto.RegisterType((*CloseStdinRequest)(nil), "grpc.CloseStdinRequest")
	proto.RegisterType((*TtyWinResizeRequest)(nil), "grpc.TtyWinResizeRequest")
	proto.RegisterType((*StartSandboxRequest)(nil), "grpc.StartSandboxRequest")
	proto.RegisterType((*DestroySandboxRequest)(nil), "grpc.DestroySandboxRequest")
	proto.RegisterType((*IpAddress)(nil), "grpc.IpAddress")
	proto.RegisterType((*UpdateInterfaceRequest)(nil), "grpc.UpdateInterfaceRequest")
	proto.RegisterType((*AddRouteRequest)(nil), "grpc.AddRouteRequest")
	proto.RegisterType((*OnlineCPUMemRequest)(nil), "grpc.OnlineCPUMemRequest")
	proto.RegisterType((*StringUser)(nil), "grpc.StringUser")
	proto.RegisterType((*Route)(nil), "grpc.Route")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion2

// Client API for HyperstartService service

type HyperstartServiceClient interface {
	// execution
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc1.CallOption) (*WaitProcessResponse, error)
	// stdio
	WriteStdin(ctx context.Context, in *WriteStreamRequest, opts ...grpc1.CallOption) (*WriteStreamResponse, error)
	ReadStdout(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error)
	ReadStderr(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error)
	CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	// misc (TODO: some rpcs can be replaced by hyperstart-exec)
	StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	OnlineCPUMem(ctx context.Context, in *OnlineCPUMemRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type hyperstartServiceClient struct {
	cc *grpc1.ClientConn
}

func NewHyperstartServiceClient(cc *grpc1.ClientConn) HyperstartServiceClient {
	return &hyperstartServiceClient{cc}
}

func (c *hyperstartServiceClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/StartContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/ExecProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/SignalProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc1.CallOption) (*WaitProcessResponse, error) {
	out := new(WaitProcessResponse)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/WaitProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) WriteStdin(ctx context.Context, in *WriteStreamRequest, opts ...grpc1.CallOption) (*WriteStreamResponse, error) {
	out := new(WriteStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/WriteStdin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) ReadStdout(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error) {
	out := new(ReadStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/ReadStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) ReadStderr(ctx context.Context, in *ReadStreamRequest, opts ...grpc1.CallOption) (*ReadStreamResponse, error) {
	out := new(ReadStreamResponse)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/ReadStderr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/CloseStdin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/TtyWinResize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/StartSandbox", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/DestroySandbox", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/UpdateInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/AddRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperstartServiceClient) OnlineCPUMem(ctx context.Context, in *OnlineCPUMemRequest, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.HyperstartService/OnlineCPUMem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HyperstartService service

type HyperstartServiceServer interface {
	// execution
	CreateContainer(context.Context, *CreateContainerRequest) (*google_protobuf.Empty, error)
	StartContainer(context.Context, *StartContainerRequest) (*google_protobuf.Empty, error)
	ExecProcess(context.Context, *ExecProcessRequest) (*google_protobuf.Empty, error)
	SignalProcess(context.Context, *SignalProcessRequest) (*google_protobuf.Empty, error)
	WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error)
	// stdio
	WriteStdin(context.Context, *WriteStreamRequest) (*WriteStreamResponse, error)
	ReadStdout(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	ReadStderr(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*google_protobuf.Empty, error)
	TtyWinResize(context.Context, *TtyWinResizeRequest) (*google_protobuf.Empty, error)
	// misc (TODO: some rpcs can be replaced by hyperstart-exec)
	StartSandbox(context.Context, *StartSandboxRequest) (*google_protobuf.Empty, error)
	DestroySandbox(context.Context, *DestroySandboxRequest) (*google_protobuf.Empty, error)
	UpdateInterface(context.Context, *UpdateInterfaceRequest) (*google_protobuf.Empty, error)
	AddRoute(context.Context, *AddRouteRequest) (*google_protobuf.Empty, error)
	OnlineCPUMem(context.Context, *OnlineCPUMemRequest) (*google_protobuf.Empty, error)
}

func RegisterHyperstartServiceServer(s *grpc1.Server, srv HyperstartServiceServer) {
	s.RegisterService(&_HyperstartService_serviceDesc, srv)
}

func _HyperstartService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).StartContainer(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/StartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_ExecProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).ExecProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/ExecProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).ExecProcess(ctx, req.(*ExecProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_SignalProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).SignalProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/SignalProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).SignalProcess(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_WaitProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).WaitProcess(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/WaitProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).WaitProcess(ctx, req.(*WaitProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_WriteStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).WriteStdin(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/WriteStdin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).WriteStdin(ctx, req.(*WriteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_ReadStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).ReadStdout(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/ReadStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).ReadStdout(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_ReadStderr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).ReadStderr(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/ReadStderr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).ReadStderr(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_CloseStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).CloseStdin(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/CloseStdin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).CloseStdin(ctx, req.(*CloseStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_TtyWinResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtyWinResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).TtyWinResize(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/TtyWinResize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).TtyWinResize(ctx, req.(*TtyWinResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_StartSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).StartSandbox(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/StartSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).StartSandbox(ctx, req.(*StartSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_DestroySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).DestroySandbox(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/DestroySandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).DestroySandbox(ctx, req.(*DestroySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_UpdateInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).UpdateInterface(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/UpdateInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).UpdateInterface(ctx, req.(*UpdateInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).AddRoute(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/AddRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperstartService_OnlineCPUMem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineCPUMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperstartServiceServer).OnlineCPUMem(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HyperstartService/OnlineCPUMem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperstartServiceServer).OnlineCPUMem(ctx, req.(*OnlineCPUMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HyperstartService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.HyperstartService",
	HandlerType: (*HyperstartServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _HyperstartService_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _HyperstartService_StartContainer_Handler,
		},
		{
			MethodName: "ExecProcess",
			Handler:    _HyperstartService_ExecProcess_Handler,
		},
		{
			MethodName: "SignalProcess",
			Handler:    _HyperstartService_SignalProcess_Handler,
		},
		{
			MethodName: "WaitProcess",
			Handler:    _HyperstartService_WaitProcess_Handler,
		},
		{
			MethodName: "WriteStdin",
			Handler:    _HyperstartService_WriteStdin_Handler,
		},
		{
			MethodName: "ReadStdout",
			Handler:    _HyperstartService_ReadStdout_Handler,
		},
		{
			MethodName: "ReadStderr",
			Handler:    _HyperstartService_ReadStderr_Handler,
		},
		{
			MethodName: "CloseStdin",
			Handler:    _HyperstartService_CloseStdin_Handler,
		},
		{
			MethodName: "TtyWinResize",
			Handler:    _HyperstartService_TtyWinResize_Handler,
		},
		{
			MethodName: "StartSandbox",
			Handler:    _HyperstartService_StartSandbox_Handler,
		},
		{
			MethodName: "DestroySandbox",
			Handler:    _HyperstartService_DestroySandbox_Handler,
		},
		{
			MethodName: "UpdateInterface",
			Handler:    _HyperstartService_UpdateInterface_Handler,
		},
		{
			MethodName: "AddRoute",
			Handler:    _HyperstartService_AddRoute_Handler,
		},
		{
			MethodName: "OnlineCPUMem",
			Handler:    _HyperstartService_OnlineCPUMem_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6f, 0x1b, 0x45,
	0x10, 0x96, 0x7b, 0x4e, 0x1a, 0x8f, 0x93, 0xa6, 0x59, 0x93, 0xf4, 0x70, 0x8b, 0x14, 0x0e, 0x89,
	0xfa, 0x05, 0x57, 0x04, 0x09, 0xa9, 0x48, 0xa8, 0x0a, 0x26, 0x0a, 0x7e, 0x28, 0xad, 0xce, 0x84,
	0xc0, 0x13, 0x6c, 0x6e, 0xa7, 0xee, 0x81, 0xbd, 0x7b, 0xec, 0xae, 0x71, 0xcd, 0x1b, 0x0f, 0xfc,
	0x25, 0xfc, 0xa3, 0xd5, 0xfe, 0xba, 0x9e, 0xed, 0x73, 0xa4, 0x56, 0x7e, 0x9b, 0x99, 0xdd, 0xfb,
	0xe6, 0x9b, 0xd9, 0xb9, 0x6f, 0xe0, 0xfe, 0xeb, 0x45, 0x81, 0x52, 0x69, 0x2a, 0x75, 0xbf, 0x90,
	0x42, 0x0b, 0xd2, 0x1c, 0xcb, 0x22, 0xeb, 0xb6, 0x44, 0x96, 0xbb, 0x40, 0xf7, 0xe1, 0x58, 0x88,
	0xf1, 0x04, 0x9f, 0x58, 0xef, 0x66, 0xf6, 0xea, 0x09, 0x4e, 0x0b, 0xbd, 0x70, 0x87, 0xc9, 0xaf,
	0x70, 0x32, 0x90, 0x48, 0x35, 0x0e, 0x04, 0xd7, 0x34, 0xe7, 0x28, 0x53, 0xfc, 0x6b, 0x86, 0x4a,
	0x93, 0x4f, 0x61, 0x3f, 0x0b, 0xb1, 0xdf, 0x72, 0x16, 0x37, 0x4e, 0x1b, 0xbd, 0x56, 0xda, 0x2e,
	0x63, 0x43, 0x46, 0x1e, 0x41, 0xf4, 0x62, 0x30, 0x8c, 0xef, 0x9c, 0x36, 0x7a, 0xed, 0x33, 0xe8,
	0x9b, 0xc4, 0xfd, 0x51, 0x81, 0x59, 0x6a, 0xc2, 0xc9, 0x37, 0x70, 0x3c, 0x32, 0xbc, 0x3e, 0x00,
	0x39, 0xf9, 0x1d, 0xc8, 0xc5, 0x1b, 0xcc, 0x5e, 0x4a, 0x91, 0xa1, 0x52, 0xef, 0x41, 0xe9, 0x31,
	0xdc, 0x2d, 0xdc, 0x47, 0x9e, 0xd6, 0x81, 0xa3, 0x15, 0x90, 0xc2, 0x69, 0x52, 0xc0, 0x47, 0xa3,
	0x7c, 0xcc, 0xe9, 0xe4, 0xfd, 0x73, 0x7c, 0x02, 0xe0, 0x51, 0xcc, 0x85, 0x3b, 0xf6, 0x42, 0xcb,
	0x47, 0x86, 0x8c, 0x9c, 0xc0, 0xae, 0xb2, 0xc8, 0x71, 0x74, 0xda, 0xe8, 0x1d, 0xa4, 0xde, 0x4b,
	0x7e, 0x06, 0x72, 0x4d, 0x73, 0xbd, 0xed, 0x7c, 0xc9, 0x17, 0xd0, 0x59, 0xc2, 0x55, 0x85, 0xe0,
	0x0a, 0x2d, 0x0d, 0x4d, 0xf5, 0x4c, 0x59, 0xc8, 0x9d, 0xd4, 0x7b, 0xc9, 0x1f, 0x40, 0xae, 0x65,
	0xae, 0x71, 0xa4, 0x25, 0xd2, 0xe9, 0xf6, 0xca, 0x26, 0xd0, 0x64, 0x54, 0x53, 0x5b, 0xf4, 0x7e,
	0x6a, 0xed, 0xe4, 0x31, 0x74, 0x96, 0x72, 0x79, 0x6a, 0xf7, 0x21, 0x9a, 0x20, 0xb7, 0x39, 0x0e,
	0x52, 0x63, 0x26, 0x63, 0x38, 0x4a, 0x91, 0xb2, 0x6d, 0x73, 0xf2, 0x89, 0xa2, 0x77, 0x89, 0x7a,
	0x40, 0xaa, 0x89, 0x3c, 0xa1, 0xc0, 0xbd, 0x51, 0xe1, 0x7e, 0x05, 0x47, 0x83, 0x89, 0x50, 0x38,
	0xd2, 0x2c, 0xe7, 0xdb, 0x7b, 0xad, 0x7f, 0x1b, 0xd0, 0xf9, 0x49, 0x2f, 0xae, 0x0d, 0xa6, 0xca,
	0xff, 0xc1, 0xad, 0x16, 0x2b, 0xc5, 0x3c, 0x14, 0x2b, 0xc5, 0xdc, 0x8c, 0x40, 0x26, 0x26, 0xb3,
	0x29, 0x8f, 0x9b, 0x6e, 0x12, 0x9d, 0x97, 0x0c, 0xa0, 0x63, 0xff, 0xcc, 0x11, 0xe5, 0xec, 0x46,
	0xbc, 0x09, 0x14, 0xba, 0xb0, 0xf7, 0x5a, 0x28, 0xcd, 0xe9, 0x14, 0x7d, 0xfa, 0xd2, 0x37, 0xe0,
	0x8c, 0x9b, 0x7f, 0x2a, 0xea, 0xb5, 0x52, 0x63, 0x26, 0x0f, 0xe0, 0xf8, 0x7b, 0x54, 0x5a, 0x8a,
	0xc5, 0x32, 0x4c, 0xf2, 0x14, 0x5a, 0xc3, 0xe2, 0x9c, 0x31, 0x89, 0x4a, 0x91, 0x18, 0xee, 0x52,
	0x67, 0x7a, 0xc8, 0xe0, 0x9a, 0x9e, 0x4f, 0xa9, 0xfa, 0xd3, 0xd7, 0x61, 0xed, 0xe4, 0xff, 0x06,
	0x9c, 0x5c, 0x15, 0x8c, 0x6a, 0x1c, 0x72, 0x8d, 0xf2, 0x15, 0xcd, 0xca, 0xfe, 0x10, 0x68, 0xea,
	0x45, 0xe1, 0x88, 0x35, 0x53, 0x6b, 0x9b, 0xfa, 0x18, 0xfe, 0x9d, 0x67, 0xe8, 0x41, 0xbc, 0x67,
	0x92, 0x72, 0x9c, 0xff, 0x68, 0xea, 0x88, 0x5c, 0x52, 0xef, 0x92, 0x2f, 0xa1, 0x9d, 0x07, 0x6e,
	0xa8, 0xe2, 0xe6, 0x69, 0xd4, 0x6b, 0x9f, 0x1d, 0x3a, 0x89, 0x28, 0x49, 0xa7, 0xd5, 0x3b, 0xa6,
	0xf2, 0xa9, 0x9e, 0xc5, 0x3b, 0x36, 0xaf, 0x31, 0x93, 0xaf, 0xe1, 0xf0, 0x9c, 0xb1, 0x54, 0xcc,
	0x74, 0xc9, 0xee, 0x33, 0xd8, 0x95, 0xc6, 0x37, 0x55, 0x1a, 0xc8, 0xb6, 0x83, 0x74, 0x77, 0xfc,
	0x51, 0x72, 0x0c, 0x9d, 0x17, 0x7c, 0x92, 0x73, 0x1c, 0xbc, 0xbc, 0x7a, 0x8e, 0x61, 0xcc, 0x93,
	0x5f, 0x00, 0x46, 0x5a, 0xe6, 0x7c, 0x7c, 0xa5, 0x50, 0x9a, 0x74, 0xb3, 0xf2, 0xf9, 0x8d, 0x69,
	0x22, 0xe3, 0xf2, 0xbd, 0x8d, 0x49, 0x3e, 0x87, 0x7b, 0x94, 0xb1, 0x5c, 0xe7, 0x82, 0xd3, 0xc9,
	0x65, 0xce, 0x54, 0x1c, 0xd9, 0x77, 0x59, 0x89, 0x26, 0xcf, 0x61, 0xc7, 0x32, 0xb0, 0xf3, 0x8d,
	0x4a, 0x7b, 0x54, 0x6b, 0x9b, 0x26, 0x8d, 0xa9, 0xc6, 0x39, 0x5d, 0x78, 0xe8, 0xe0, 0x56, 0xda,
	0x1a, 0x55, 0xdb, 0x7a, 0xf6, 0xdf, 0x1e, 0x1c, 0xfd, 0x50, 0xae, 0x9b, 0x11, 0x4a, 0xdb, 0xec,
	0x4b, 0x38, 0x5c, 0xd9, 0x20, 0xe4, 0x91, 0xab, 0xbe, 0x7e, 0xb1, 0x74, 0x4f, 0xfa, 0x6e, 0x21,
	0xf5, 0xc3, 0x42, 0xea, 0x5f, 0x98, 0x85, 0x44, 0x2e, 0xe0, 0xde, 0xf2, 0xbe, 0x20, 0x0f, 0xfd,
	0x4a, 0xa9, 0xdb, 0x22, 0x1b, 0x61, 0x9e, 0x41, 0xbb, 0xb2, 0x3a, 0x48, 0xec, 0x30, 0xd6, 0xb7,
	0xc9, 0x46, 0x80, 0x01, 0x1c, 0x2c, 0x6d, 0x06, 0xd2, 0xf5, 0x34, 0x6a, 0xd6, 0xc5, 0x46, 0x90,
	0xef, 0xa0, 0x5d, 0x11, 0xe5, 0xc0, 0x62, 0x5d, 0xff, 0xbb, 0x1f, 0xd7, 0x9c, 0x78, 0x55, 0x3a,
	0x07, 0xf0, 0xea, 0xc9, 0x72, 0x5e, 0x42, 0xac, 0x69, 0x77, 0x09, 0x51, 0xa3, 0xb4, 0xcf, 0x00,
	0x9c, 0xdc, 0x31, 0x31, 0xd3, 0xe4, 0x81, 0x9f, 0xca, 0x55, 0xa5, 0xed, 0xc6, 0xeb, 0x07, 0x6b,
	0x00, 0x28, 0xe5, 0x87, 0x00, 0x7c, 0x0b, 0xf0, 0x4e, 0x46, 0x03, 0xc0, 0x9a, 0xb0, 0x6e, 0xec,
	0xe3, 0x39, 0xec, 0x57, 0xd5, 0x92, 0xf8, 0x5a, 0x6b, 0x14, 0xf4, 0x36, 0x88, 0xaa, 0xda, 0x05,
	0x88, 0x1a, 0x05, 0xbc, 0x6d, 0x34, 0x97, 0xb5, 0x2e, 0x8c, 0x66, 0xad, 0x02, 0x6e, 0x84, 0xb9,
	0x84, 0xc3, 0x15, 0x75, 0x0b, 0xbf, 0x4a, 0xbd, 0xe8, 0x6d, 0x04, 0x7a, 0x0a, 0x7b, 0x41, 0x81,
	0xc8, 0xb1, 0x43, 0x58, 0x51, 0xa4, 0xdb, 0xba, 0x51, 0x15, 0xa1, 0xd0, 0x8d, 0x1a, 0x61, 0xda,
	0x04, 0x71, 0xb3, 0x6b, 0xfd, 0xaf, 0xde, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xb3, 0x68, 0x55,
	0x7c, 0x0a, 0x00, 0x00,
}
